### ISSUE TITLE
Failing to build Arpack

### ISSUE THREAD

**Issue by XVilka** [QuantEcon/QuantEconLectureAllPackages#8] opened 2019-04-18 18:27 UTC
If I run installation with `activate_github` it returns the following error:
```julia
activate_github("QuantEcon/QuantEconLectureAllPackages", tag = "v0.9.8", add_default_environment = true)
```
```
  Building Arpack ──────────→ `~/.julia/packages/Arpack/UiiMc/deps/build.log`
┌ Error: Error building `Arpack`: 
│ [ Info: Downloading https://github.com/JuliaLinearAlgebra/ArpackBuilder/releases/download/v3.5.0-3/Arpack.v3.5.0-3.x86_64-linux-gnu-gcc8.tar.gz to /home/xvilka/.julia/packages/Arpack/UiiMc/deps/usr/downloads/Arpack.v3.5.0-3.x86_64-linux-gnu-gcc8.tar.gz...
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/xvilka/.julia/packages/Arpack/UiiMc/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/xvilka/.julia/packages/BinaryProvider/4F5Hq/src/Products.jl:414
│  [2] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [3] top-level scope at none:0
│  [4] include(::String) at ./client.jl:403
│  [5] top-level scope at none:0
│ in expression starting at /home/xvilka/.julia/packages/Arpack/UiiMc/deps/build.jl:74
[18:42:36] ######################################################################## 100.0% 
└ @ Pkg.Operations /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
```
then after a while this (I guess it is a consequence of failed Arpack package installation:
```
[ Info: Precompiling RegressionTables [d519eb52-b820-54da-95a6-98e1306fdade]
ERROR: LoadError: No deps.jl file could be found. Please try running Pkg.build("Arpack").
Currently, the build command might fail when Julia has been built from source
and the recommendation is to use the official binaries from julialang.org.
For more info see https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5.

Stacktrace:
 [1] top-level scope at /home/xvilka/.julia/packages/Arpack/UiiMc/src/Arpack.jl:19
 [2] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/Arpack/UiiMc/src/Arpack.jl:16
ERROR: LoadError: LoadError: Failed to precompile Arpack [7d9fca2a-8960-54d3-9f78-7d1dccf2cb97] to /home/xvilka/.julia/compiled/v1.1/Arpack/X5VZL.ji.
Stacktrace:
 [1] include at ./sysimg.jl:29 [inlined]
 [2] include(::String) at /home/xvilka/.julia/packages/PDMats/Kouno/src/PDMats.jl:1
 [3] top-level scope at /home/xvilka/.julia/packages/PDMats/Kouno/src/PDMats.jl:52
 [4] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/PDMats/Kouno/src/pdsparsemat.jl:1
in expression starting at /home/xvilka/.julia/packages/PDMats/Kouno/src/PDMats.jl:51
ERROR: LoadError: Failed to precompile PDMats [90014a1f-27ba-587c-ab20-58faa44d9150] to /home/xvilka/.julia/compiled/v1.1/PDMats/wuzEE.ji.
Stacktrace:
 [1] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/Distributions/fMt8c/src/Distributions.jl:3
ERROR: LoadError: Failed to precompile Distributions [31c24e10-a181-5473-b8eb-7969acd0382f] to /home/xvilka/.julia/compiled/v1.1/Distributions/xILW0.ji.
Stacktrace:
 [1] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/RegressionTables/TSQTA/src/RegressionTables.jl:38
ERROR: Failed to precompile RegressionTables [d519eb52-b820-54da-95a6-98e1306fdade] to /home/xvilka/.julia/compiled/v1.1/RegressionTables/cYvie.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [2] precompile(::Pkg.Types.Context) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:429
 [3] do_precompile!(::Dict{Symbol,Any}, ::Array{String,1}, ::Dict{Symbol,Any}) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:612
 [4] do_cmd!(::Pkg.REPLMode.PkgCommand, ::Pkg.REPLMode.MiniREPL) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:561
 [5] #do_cmd#30(::Bool, ::Function, ::Pkg.REPLMode.MiniREPL, ::String) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:536
 [6] #do_cmd at ./sysimg.jl:0 [inlined]
 [7] #activate_github#1(::String, ::Nothing, ::Bool, ::Bool, ::Function, ::String) at /home/xvilka/.julia/packages/InstantiateFromURL/mpsrf/src/activate.jl:52
 [8] (::getfield(InstantiateFromURL, Symbol("#kw##activate_github")))(::NamedTuple{(:tag, :add_default_environment),Tuple{String,Bool}}, ::typeof(activate_github), ::String) at ./none:0
 [9] top-level scope at none:0

julia> 
```
I am using Gentoo x86_64 with GCC 8.3.0 and LLVM-8.0.0. Libarpack is installed:
```
localhost /home/xvilka # eix arpack
[I] sci-libs/arpack
     Available versions:  3.1.5 (~)3.4.0 (~)3.5.0 **9999 {doc examples mpi static-libs}
     Installed versions:  3.5.0(12:20:19 AM 03/21/2019)(-doc -examples -mpi -static-libs)
     Homepage:            http://www.caam.rice.edu/software/ARPACK/ https://github.com/opencollab/arpack-ng
     Description:         Arnoldi package library to solve large scale eigenvalue problems

localhost /home/xvilka #
```

**Comment by arnavs** [comment] 2019-04-18 18:35
Hey, thanks for filing this issue. Weirdly, I can't reproduce with Ubuntu. 

```
julia> activate_github("QuantEcon/QuantEconLectureAllPackages", tag = "v0.9.8", add_default_environment = true, force = true)
Downloading QuantEcon/QuantEconLectureAllPackages-v0.9.8 → /home/arnavsood/.projects
-=O=- #       #        #           #                                                                                                                                                                                             
Instantiating /home/arnavsood/.projects/QuantEconLectureAllPackages-v0.9.8
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Precompiling project...
Precompiling LazyArrays
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/LazyArrays/h0pkJ.ji for LazyArrays [5078a376-72f3-5289-bfd5-ec5146d43c02]
Precompiling Expectations
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/Expectations/r1e2K.ji for Expectations [2fe49d83-0758-5602-8f54-1f90ad0d522b]
Precompiling GR
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/GR/NDU5Y.ji for GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]
Precompiling Revise
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/Revise/M1Qoh.ji for Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
[ Info: Generating builtins for this julia version...
Precompiling Plots
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
Precompiling Roots
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/Roots/o0Xsi.ji for Roots [f2b01f46-fcfa-551c-844a-d8ac1e96c665]
Precompiling NLsolve
[ Info: Recompiling stale cache file /home/arnavsood/.julia/compiled/v1.1/NLsolve/KFCNP.ji for NLsolve [2774e3e8-f4cf-5e23-947b-6d7e65073b56]
Adding to the default environment... pkglist = Array{String}(collect(keys(packages))) = ["ForwardDiff", "DataVoyager", "RegressionTables", "LazyArrays", "VegaDatasets", "Compat", "FixedEffectModels", "CategoricalArrays", "Latexify", "Expectations", "DataFrames", "LeastSquaresOptim", "StatsModels", "GR", "Distributions", "VegaLite", "FastGaussQuadrature", "LinearAlgebra", "Queryverse", "KernelDensity", "ColorTypes", "Polynomials", "ProgressMeter", "Revise", "Test", "Random", "Sundials", "BenchmarkTools", "Optim", "StatsPlots", "Conda", "Traceur", "BandedMatrices", "DataFramesMeta", "StatsBase", "Flux", "Plots", "DiffEqCallbacks", "QuadGK", "BlackBoxOptim", "StaticArrays", "DifferentialEquations", "Parameters", "DiffEqDiffTools", "GLM", "Statistics", "LightGraphs", "Interpolations", "JuMP", "Query", "Roots", "Ipopt", "NLopt", "LaTeXStrings", "PkgTemplates", "SparseArrays", "RDatasets", "NLsolve", "QuantEcon", "FillArrays"]
 Resolving package versions...
  Updating `~/.julia/environments/v1.1/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.1/Manifest.toml`
 [no changes]
("v0.9.8", "/home/arnavsood/.projects/QuantEconLectureAllPackages-v0.9.8", Dict{String,Any}("ForwardDiff"=>"f6369f11-7733-5829-9624-2563aa707210","DataVoyager"=>"5721bf48-af8e-5845-8445-c9e18126e773","RegressionTables"=>"d519eb52-b820-54da-95a6-98e1306fdade","LazyArrays"=>"5078a376-72f3-5289-bfd5-ec5146d43c02","VegaDatasets"=>"0ae4a718-28b7-58ec-9efb-cded64d6d5b4","Compat"=>"34da2185-b29b-5c13-b0c7-acf172513d20","FixedEffectModels"=>"9d5cd8c9-2029-5cab-9928-427838db53e3","CategoricalArrays"=>"324d7699-5711-5eae-9e2f-1d82baa6b597","Latexify"=>"23fbe1c1-3f47-55db-b15f-69d7ec21a316","Expectations"=>"2fe49d83-0758-5602-8f54-1f90ad0d522b"…))

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Also, this version was produced to test some infrastructure stuff on our end. You should probably stick with whatever's tagged in the Julia lecture versions we have online (if you found your way here from there.) Sorry, should've been clearer about this. 

Will leave open. I think Mac will have an issue with this release because of issues with the `Homebrew.jl` package manager? We'll see.

**Comment by arnavs** [comment] 2019-04-18 18:36
Also, just to confirm, is your Julia built from source/have you `] dev`ed any of these packages? Because what I get is: 

```
(QuantEconLectureAllPackages) pkg> build Arpack
  Building Arpack → `~/.julia/packages/Arpack/UiiMc/deps/build.log`

(QuantEconLectureAllPackages) pkg> build RegressionTables
  Building CodecZlib ───────→ `~/.julia/packages/CodecZlib/9jDi1/deps/build.log`
  Building Arpack ──────────→ `~/.julia/packages/Arpack/UiiMc/deps/build.log`
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building Rmath ───────────→ `~/.julia/packages/Rmath/Py9gH/deps/build.l
```

**Comment by XVilka** [comment] 2019-04-18 19:12
My Julia is Gentoo package (latest release), but the rest is built locally.

**Comment by arnavs** [comment] 2019-04-24 17:37
Hey @XVilka are you still having this issue? And have you tried reverting to the version tagged in the public lectures? If those are failing, that's a more serious issue.

**Comment by XVilka** [comment] 2019-04-25 15:37
@arnavs just tried to compile 0.9.6 version (the one from lectures), seems error is still there:
```
Precompiling project...
Precompiling ForwardDiff
[ Info: Recompiling stale cache file /home/xvilka/.julia/compiled/v1.1/ForwardDiff/k0ETY.ji for ForwardDiff [f6369f11-7733-5829-9624-2563aa707210]
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
Precompiling DataVoyager
[ Info: Recompiling stale cache file /home/xvilka/.julia/compiled/v1.1/DataVoyager/5nnU1.ji for DataVoyager [5721bf48-af8e-5845-8445-c9e18126e773]
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
Precompiling RegressionTables
[ Info: Precompiling RegressionTables [d519eb52-b820-54da-95a6-98e1306fdade]
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
Precompiling LazyArrays
[ Info: Precompiling LazyArrays [5078a376-72f3-5289-bfd5-ec5146d43c02]
Precompiling VegaDatasets
[ Info: Precompiling VegaDatasets [0ae4a718-28b7-58ec-9efb-cded64d6d5b4]
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
┌ Warning: Module Compat with build ID 241644450597254 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:947
Precompiling FixedEffectModels
[ Info: Precompiling FixedEffectModels [9d5cd8c9-2029-5cab-9928-427838db53e3]
ERROR: LoadError: No deps.jl file could be found. Please try running Pkg.build("Arpack").
Currently, the build command might fail when Julia has been built from source
and the recommendation is to use the official binaries from julialang.org.
For more info see https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5.

Stacktrace:
 [1] top-level scope at /home/xvilka/.julia/packages/Arpack/UiiMc/src/Arpack.jl:19
 [2] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/Arpack/UiiMc/src/Arpack.jl:16
ERROR: LoadError: LoadError: Failed to precompile Arpack [7d9fca2a-8960-54d3-9f78-7d1dccf2cb97] to /home/xvilka/.julia/compiled/v1.1/Arpack/X5VZL.ji.
Stacktrace:
 [1] include at ./sysimg.jl:29 [inlined]
 [2] include(::String) at /home/xvilka/.julia/packages/PDMats/Kouno/src/PDMats.jl:1
 [3] top-level scope at /home/xvilka/.julia/packages/PDMats/Kouno/src/PDMats.jl:52
 [4] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/PDMats/Kouno/src/pdsparsemat.jl:1
in expression starting at /home/xvilka/.julia/packages/PDMats/Kouno/src/PDMats.jl:51
ERROR: LoadError: Failed to precompile PDMats [90014a1f-27ba-587c-ab20-58faa44d9150] to /home/xvilka/.julia/compiled/v1.1/PDMats/wuzEE.ji.
Stacktrace:
 [1] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/Distributions/WHjOk/src/Distributions.jl:3
ERROR: LoadError: Failed to precompile Distributions [31c24e10-a181-5473-b8eb-7969acd0382f] to /home/xvilka/.julia/compiled/v1.1/Distributions/xILW0.ji.
Stacktrace:
 [1] top-level scope at none:2
in expression starting at /home/xvilka/.julia/packages/FixedEffectModels/Jn6lk/src/FixedEffectModels.jl:14
ERROR: Failed to precompile FixedEffectModels [9d5cd8c9-2029-5cab-9928-427838db53e3] to /home/xvilka/.julia/compiled/v1.1/FixedEffectModels/XFTup.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [2] precompile(::Pkg.Types.Context) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:429
 [3] do_precompile!(::Dict{Symbol,Any}, ::Array{String,1}, ::Dict{Symbol,Any}) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:612
 [4] do_cmd!(::Pkg.REPLMode.PkgCommand, ::Pkg.REPLMode.MiniREPL) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:561
 [5] #do_cmd#30(::Bool, ::Function, ::Pkg.REPLMode.MiniREPL, ::String) at /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/REPLMode.jl:536
 [6] #do_cmd at ./sysimg.jl:0 [inlined]
 [7] #activate_github#1(::String, ::Nothing, ::Bool, ::Bool, ::Function, ::String) at /home/xvilka/.julia/packages/InstantiateFromURL/mpsrf/src/activate.jl:52
 [8] (::getfield(InstantiateFromURL, Symbol("#kw##activate_github")))(::NamedTuple{(:tag, :add_default_environment),Tuple{String,Bool}}, ::typeof(activate_github), ::String) at ./none:0
 [9] top-level scope at none:0

julia> using Pkg

julia> Pkg.build("Arpack")
  Building Arpack → `~/.julia/packages/Arpack/UiiMc/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/xvilka/.julia/packages/Arpack/UiiMc/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/xvilka/.julia/packages/BinaryProvider/4F5Hq/src/Products.jl:414
│  [2] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [3] top-level scope at none:0
│  [4] include(::String) at ./client.jl:403
│  [5] top-level scope at none:0
│ in expression starting at /home/xvilka/.julia/packages/Arpack/UiiMc/deps/build.jl:74
└ @ Pkg.Operations /var/tmp/portage/dev-lang/julia-1.1.0/work/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

julia> 

```

**Comment by arnavs** [comment] 2019-04-25 15:39
Roger that. Guess this is a push to widen the set of operating systems we test on `:-)`. 

I'll explore and get back to you.

**Comment by jlperla** [comment] 2019-04-25 17:49
@XVilka does this have anything to do with QuantEcon packages, or is it a setup issue with Arpack binaries and your system?  

i.e. if you start from a fresh project.toml file, not activating the julia one, can you go `add Arpack` and see errors, or `] build Arpack` or whatever if it is already installed?

**Comment by XVilka** [comment] 2019-05-03 02:19
WIll retry in a few days - travelling now.

**Comment by XVilka** [comment] 2019-05-07 08:53
I checked with 0.9.8 tag with Fedora 30 - everything is fine. Will check on my Gentoo soon.

**Comment by arnavs** [comment] 2019-05-07 16:48
Sounds good. In that case, I'll close this issue, because sadly we don't have the bandwidth to support all the different Linux distributions. 

If you can pinpoint what needs to be fixed, though, maybe we could forward it along to the Arpack people. I'll add a small note to the README in the meantime, clarifying what we test/support.

**Closed by arnavs** 2019-05-07 16:48 UTC
